# Generated by Django 5.2.8 on 2025-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="Tag_line",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
