# Generated by Django 5.2.8 on 2025-11-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_annualreport_award_boardmember_calltoaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="Tag_line",
            new_name="tag_line",
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "footer_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="website.footercolumn",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
