# Generated by Django 5.2.8 on 2025-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_footercolumn_rename_tag_line_sitesettings_tag_line_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annualreport",
            name="file_url",
        ),
        migrations.RemoveField(
            model_name="resourceitem",
            name="file_url",
        ),
        migrations.AddField(
            model_name="annualreport",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="files/annual_reports/"
            ),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="files/resources/"),
        ),
        migrations.AlterField(
            model_name="award",
            name="icon_svg",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons/"),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/board/"),
        ),
        migrations.AlterField(
            model_name="calltoaction",
            name="background_svg",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/backgrounds/"
            ),
        ),
        migrations.AlterField(
            model_name="carouselitem",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/carousel/"
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="icon_svg",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons/"),
        ),
        migrations.AlterField(
            model_name="member",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/members/"),
        ),
        migrations.AlterField(
            model_name="memberspotlight",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/members/"),
        ),
        migrations.AlterField(
            model_name="quickaccesscard",
            name="icon_svg",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons/"),
        ),
        migrations.AlterField(
            model_name="researchhighlight",
            name="lead_researcher_image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/researchers/"
            ),
        ),
        migrations.AlterField(
            model_name="statisticcounter",
            name="icon_svg",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons/"),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="presenter_image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/presenters/"
            ),
        ),
    ]
