# Generated by Django 5.2.8 on 2025-11-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_remove_annualreport_file_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="background_svg",
        ),
        migrations.AddField(
            model_name="herosection",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/hero/"),
        ),
    ]
