# Generated by Django 4.2.7 on 2025-11-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_remove_herosection_background_svg_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calltoaction",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="calltoaction",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
