# Generated by Django 5.2.8 on 2025-11-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_calltoaction_options_calltoaction_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="researchhighlight",
            old_name="profile_url",
            new_name="journal_link",
        ),
        migrations.AddField(
            model_name="researchhighlight",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchhighlight",
            name="journal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
