# Generated by Django 5.2.8 on 2025-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_rename_profile_url_researchhighlight_journal_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
