# Generated by Django 4.2.7 on 2025-11-29 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_organizationalvalue"),
        ("website", "0009_sitesettings_contact_mail_sitesettings_location_and_more"),
    ]

    operations = []
