# Generated by ChatGPT - add TimelineSection and TimelineItem
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_merge_20251129_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
                ('icon_svg', models.ImageField(blank=True, null=True, upload_to='images/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_svg', models.ImageField(blank=True, null=True, upload_to='images/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.timelinesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
