# Generated by Django 5.2.8 on 2025-12-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_timeline_section_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footerlink",
            name="footer_column",
        ),
        migrations.RenameField(
            model_name="partnership",
            old_name="logo_url",
            new_name="link_url",
        ),
        migrations.AddField(
            model_name="partnership",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/partnership/"
            ),
        ),
        migrations.AlterField(
            model_name="timelineitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timelinesection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="FooterColumn",
        ),
        migrations.DeleteModel(
            name="FooterLink",
        ),
    ]
