# Generated by Django 5.2.8 on 2025-12-01 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_remove_footerlink_footer_column_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="image_url",
            new_name="image",
        ),
    ]
