# Generated by Django 5.2.8 on 2025-12-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_rename_image_url_member_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchInterestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
