# Generated by Django 4.2.7 on 2025-12-01 06:33

from django.db import migrations, models
import django.db.models.deletion


def create_defaults_and_populate(apps, schema_editor):
    """Create default Speciality and ResearchInterestArea, then populate existing members"""
    Speciality = apps.get_model('website', 'Speciality')
    ResearchInterestArea = apps.get_model('website', 'ResearchInterestArea')
    Member = apps.get_model('website', 'Member')
    
    # Create default Speciality if it doesn't exist
    others_specialty, _ = Speciality.objects.get_or_create(
        name='Others',
        defaults={'description': 'Other specialties'}
    )
    
    # Create default ResearchInterestArea if it doesn't exist
    targeted_therapy, _ = ResearchInterestArea.objects.get_or_create(
        name='Targeted Therapy',
        defaults={'description': 'Targeted Therapy research'}
    )
    
    # Assign default specialty to all members who don't have one
    for member in Member.objects.all():
        if not member.specialty_fk:
            member.specialty_fk = others_specialty
            member.save()
        # Add default research interest area to all members
        member.research_interest_areas.add(targeted_therapy)


def reverse_function(apps, schema_editor):
    """Reverse function - do nothing for now"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_researchinterestarea_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="research_interest_areas",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="website.researchinterestarea"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="specialty_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_specialty",
                to="website.speciality",
            ),
        ),
        migrations.RunPython(create_defaults_and_populate, reverse_function),
    ]
