# Generated by Django 4.2.7 on 2025-12-01 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_member_research_interest_areas_member_specialty_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="member",
            name="tags",
        ),
    ]
