# Generated by Django 4.2.7 on 2025-12-01 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_remove_member_specialty_remove_member_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="research_interest",
        ),
    ]
