# Generated by Django 5.2.8 on 2025-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_remove_member_specialty_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="type",
            field=models.CharField(
                choices=[
                    ("perceptorship", "Percepetoship"),
                    ("webinar", "Webinar"),
                    ("gci", "GCI"),
                    ("other", "Other"),
                ],
                default="webinar",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="calltoaction",
            name="page",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("about", "About"),
                    ("knowledge_center", "Knowledge Center"),
                    ("member_directory", "Member Directory"),
                    ("news_and_updates", "News and Updates"),
                    ("research_and_publications", "Research and Publications"),
                    ("webinars", "Webinars"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="page",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("about", "About"),
                    ("knowledge_center", "Knowledge Center"),
                    ("member_directory", "Member Directory"),
                    ("news_and_updates", "News and Updates"),
                    ("research_and_publications", "Research and Publications"),
                    ("webinars", "Webinars"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quickaccesscard",
            name="page",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("about", "About"),
                    ("knowledge_center", "Knowledge Center"),
                    ("member_directory", "Member Directory"),
                    ("news_and_updates", "News and Updates"),
                    ("research_and_publications", "Research and Publications"),
                    ("webinars", "Webinars"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="statisticcounter",
            name="page",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("about", "About"),
                    ("knowledge_center", "Knowledge Center"),
                    ("member_directory", "Member Directory"),
                    ("news_and_updates", "News and Updates"),
                    ("research_and_publications", "Research and Publications"),
                    ("webinars", "Webinars"),
                ],
                max_length=50,
            ),
        ),
    ]
