# Generated by Django 4.2.7 on 2025-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_webinar_type_alter_calltoaction_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/panelists/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="webinar",
            name="international_panel",
            field=models.ManyToManyField(
                blank=True,
                related_name="international_panel_webinars",
                to="website.panelist",
            ),
        ),
        migrations.AddField(
            model_name="webinar",
            name="moderators",
            field=models.ManyToManyField(
                blank=True, related_name="moderated_webinars", to="website.panelist"
            ),
        ),
        migrations.AddField(
            model_name="webinar",
            name="national_panel",
            field=models.ManyToManyField(
                blank=True,
                related_name="national_panel_webinars",
                to="website.panelist",
            ),
        ),
    ]
