# Generated by Django 4.2.7 on 2025-12-01 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0022_panelist_webinar_international_panel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="panelist",
            old_name="title",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="webinar",
            old_name="presenter_image_url",
            new_name="presenter_image",
        ),
    ]
