# Generated by Django 4.2.7 on 2025-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_rename_title_panelist_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panelist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
