# Generated by Django 4.2.7 on 2025-12-01 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0024_alter_panelist_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="panelist",
            options={},
        ),
        migrations.RemoveField(
            model_name="panelist",
            name="order",
        ),
    ]
