# Generated by Django 5.2.8 on 2025-12-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0025_alter_panelist_options_remove_panelist_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourceitem",
            name="rating",
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
